steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image:$SHORT_SHA', '.' ]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image:$SHORT_SHA"]


#   # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args: 
  - run
  - --filename=kube-file.yaml
  - --image=us-west2-docker.pkg.dev/$PROJECT_ID/quickstart-docker-repo/quickstart-image:$SHORT_SHA
  - --location=us-west2-a
  - --cluster=rcl-cluster
